esphome:
  name: esphome-cam-printer1
  friendly_name: ESPHome_Cam_Printer1

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wRRBIzbVI6Qw3xXV6akcYdLXl0XnPwAIZhRQguLXy2Y="

ota:
  - platform: esphome
    password: "5a55c00ea731c101bda507657ce2c7ad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Cam-Printer1"
    password: "ERHuIOHdYc2d"

captive_portal:
    