######################################################
# Loads default set of integrations.
default_config:
logger:
  default: info

######################################################
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

######################################################
# Wake on LAN service (used by switch.victus)
wake_on_lan:

######################################################
# Includes
automation: !include automations.yaml
group: !include .includes/group.yaml

mqtt:
  switch: !include_dir_merge_list .includes/mqtt/switch/
  sensor: !include_dir_merge_list .includes/mqtt/sensor/
  binary_sensor: !include_dir_merge_list .includes/mqtt/binary_sensor/

script: !include_dir_merge_named .includes/script/
sensor: !include_dir_merge_list .includes/sensor/
shell_command: !include .includes/shell_command.yaml
template: !include_dir_merge_list .includes/template/
rest_command: !include .includes/rest_command.yaml
utility_meter: !include .includes/utility_meter.yaml
