sensor:
  - name: "MQTT Timestamp Kottbo"
    state_topic: "kottbo/timestamp"
    device_class: "timestamp"
    value_template: "{{ as_datetime(value) }}"
    unique_id: "mqtt_timestamp_kottbo"
    qos: 2
  - name: "MQTT Timestamp Quarry"
    state_topic: "quarry/timestamp"
    device_class: "timestamp"
    value_template: "{{ as_datetime(value) }}"
    unique_id: "mqtt_timestamp_quarry"
    qos: 2

binary_sensor:
  - name: "dark"
    state_topic: "home/state/dark"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 2
  - name: "evening"
    state_topic: "home/state/evening"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 2
  - name: "morning"
    state_topic: "home/state/morning"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 2

switch:
##############################################
## Home
##############################################
    - name: home_mqtt_alarm_lock
      unique_id: home_mqtt_alarm_lock
      command_topic: "home/alarm/mqtt_alarm_lock"
      state_topic: "home/alarm/mqtt_alarm_lock"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true
    - name: home_mqtt_alarm_state
      unique_id: home_mqtt_alarm_state
      command_topic: "home/alarm/mqtt_alarm_state"
      state_topic: "home/alarm/mqtt_alarm_state"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true
    - name: home_mqtt_desktop
      unique_id: home_mqtt_desktop
      command_topic: "home/switch/mqtt_desktop"
      state_topic: "home/switch/mqtt_desktop"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true
    - name: home_mqtt_xbox
      unique_id: home_mqtt_xbox
      command_topic: "home/switch/mqtt_xbox"
      state_topic: "home/switch/mqtt_xbox"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true
    - name: home_mqtt_carheat
      unique_id: home_mqtt_carheat
      command_topic: "home/switch/mqtt_carheat"
      state_topic: "home/switch/mqtt_carheat"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true
    - name: home_mqtt_evening_lights
      unique_id: home_mqtt_evening_lights
      command_topic: "home/switch/evening_lights"
      state_topic: "home/switch/evening_lights"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true
    - name: home_mqtt_morning_lights
      unique_id: home_mqtt_morning_lights 
      command_topic: "home/switch/morning_lights"
      state_topic: "home/switch/morning_lights"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true


##############################################
## Kottbo
##############################################
    - name: kottbo_mqtt_alarm_state
      unique_id: kottbo_mqtt_alarm_state
      command_topic: "kottbo/alarm/mqtt_alarm_state"
      state_topic: "kottbo/alarm/mqtt_alarm_state"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2
      retain: true


##############################################
## Victus
##############################################
    - name: victus_sleep
      unique_id: victus_sleep
      command_topic: "HASS.Agent/switch/VICTUS/sleep/state"
      state_topic: "HASS.Agent/switch/VICTUS/sleep/state"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 2