
#####################################################
# HA config
default_config:

#####################################################
# HACS Remote Home-Assistant
remote_homeassistant:
  instances:

#####################################################
# Includes
automation: !include automations.yaml
command_line: !include .includes/command_line.yaml
homeassistant: !include .includes/homeassistant.yaml
http: !include .includes/http.yaml
influxdb: !include .includes/influxdb.yaml
mqtt: !include .includes/mqtt.yaml
sensor: !include .includes/sensor.yaml
shell_command: !include .includes/shell_command.yaml
template: !include_dir_merge_list .includes/templates/