substitutions:
  device_name: buzzer-1
  friendly_name: "Buzzer 1"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

packages:
  common: !include common/common.yaml

globals:
  - id: fw_version
    type: std::string
    restore_value: no
    initial_value: '"v1.0"'

output:
  - platform: ledc
    pin: GPIO8
    id: buzzer_out
    inverted: true

rtttl:
  id: buzzer_rtttl
  output: buzzer_out
  gain: 10%

button:
  - platform: template
    name: "Buzzer beep"
    icon: "mdi:bell-ring"
    on_press:
      - rtttl.play: "dingdong:d=4,o=5,b=240:e6,c5,e6,c5"