
esphome:
  name: esphome-cam-3dprinter1
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

esp32_camera:
  id: espcam
  name: esphome-cam-3dprinter1
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  resolution: 800x600
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false
  max_framerate: 5 fps
  idle_framerate: 0.2 fps

esp32_camera_web_server:
  port: 8080
  mode: stream
