wifi_ssid: "HomeAtMyStreet"
wifi_password: "AngryCa!rn"
fallback_ssid: "ESP_Fallback"
fallback_password: ""

encryption_key: "mgpu6zIYF5wY405xrAn4B7iHerGppVamtJPePCbKAFs="
ota_password: "038ce939a13585e2d6c476f4e0be632e"